version: '3'
services:
  datadog-agent:
    image: datadog/agent:latest
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /proc/:/host/proc/:ro
      - /sys/fs/cgroup/:/host/sys/fs/cgroup:ro
    ports:
      - 8126:8126/tcp
    environment:
      - DD_APM_ENABLED=true
      - DD_APM_NON_LOCAL_TRAFFIC=true
      - DD_API_KEY=${DD_API_KEY}      
  dynamodb:
    image: amazon/dynamodb-local:latest
    ports:
      - "8000:8000"
  pynamodb-script:
    build: .
    command: bash
    environment:
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - DD_AGENT_HOST=datadog-agent
      - DATADOG_TRACE_DEBUG=true
    depends_on:
      - dynamodb
      - datadog-agent